# Generated by Django 3.2.16 on 2023-02-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230226_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('2023', '2023')], default='normal', max_length=12),
        ),
    ]
